---
 - name: Copy jar file
   copy: src=/tmp/deploy.war dest=/home/ycard/application_files/ycard-new.war owner=ycard group=ycard mode=0644

 - name: stop tomcat
   shell: /var/lib/tomcat/webapps/stop.sh

 - name: check if tomcat process is not running 
   command: "echo stopped "

 - name: Take backup of current Ycard.war file
   command: "mv /var/lib/tomcat/webapps/ycard.war /home/ycard/application_files/backup/yard.war-bakup"

 - name: Copy new war file to webapps
   command: mv /home/ycard/application_files/ycard-new.war /var/lib/tomcat/webapps/ycard.war

 - name: start tomcat
   command: /var/lib/tomcat/webapps/start.sh

 - name: Make sure process is running
   shell: ps -ef|grep sleep
   register: results

 - name: verify ps results
   debug: results
