---
 - name: Copy jar file from Control server to remote appserver
   copy: src={{tmp_bin_in_control}}/{{ycard_service_version_jar}} dest={{remote_temp_dest}}/{{ycard_service_version_jar}} owner={{deploy_user}} group={{deploy_group}} mode=0644

 - name: stop tomcat
   shell: "{{ service_tomcat }}/bin/shutdown.sh"

 - name: check if tomcat process is not running 
   shell: ps -ef|grep {{ service_tomcat }}
   register: ps_result
   ignore_errors: false
 - name: If still running, wait for 2 mins and kill the process

 - name: Check the process once again, if still running, fail it here

 - debug: msg="{{ps_result.stdout}}"
 - debug: msg="{{ps_result.stderr}}"

 - name: Take backup of current Ycard.war file
   command: "mv {{service_tomcat}}/webapps/{{ycard_service_jar}} {{remote_app_backup_dir}}/{{ycard_service_jar}}-backup"

 - name: Copy new war file to webapps
   command: mv {{remote_temp_dest}}/{{ycard_service_version_jar}} {{service_tomcat}}/webapps/{{ycard_service_jar}} 

 - name: start tomcat
   shell: "{{service_tomcat}}/../bin/startup.sh"

 - name: Make sure process is running
   shell: ps -ef|grep sleep
   register: results

 - name: verify ps results
   debug: results

 - name: If process is not running, wait for 2 mins 

 - name: Check if port is open and listening 

 - name: post deploy health checks
